#!/bin/bash

# Définir les permissions d'exécution sur l'application
chmod +x "/Applications/macOS_downloader.app/Contents/MacOS/macOS_downloader"

# Créer le dossier de logs avec les bonnes permissions
mkdir -p /var/tmp
chmod 777 /var/tmp

# Vérifier et installer unzip si nécessaire
if ! command -v unzip &> /dev/null; then
    echo "Installation de unzip..."
    if command -v brew &> /dev/null; then
        brew install unzip
    else
        echo "Homebrew non trouvé. Veuillez installer unzip manuellement."
    fi
fi

exit 0
